# Generated by Django 5.1.3 on 2024-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsubject',
            name='subject',
            field=models.TextField(),
        ),
    ]
